name: Transsion Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Download URL"
        required: true
      password:
        description: "Password"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: 🚀 Run downloader
        env:
          URL: ${{ github.event.inputs.url }}
          PASSWORD: ${{ github.event.inputs.password }}
        run: python transsion.py

      - name: 📤 Upload result link
        uses: actions/upload-artifact@v4
        with:
         name: pixeldrain-link
         path: result.txt
     
